INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Sex Doll Torso for Men – 3-in-1 Torso Sex Doll with Lifelike Skin & Built-in Skeleton, Unlocking Intense Orgasms with No Electricity Needed to Explore All Sex Positions', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_86064a45.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 10, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Huge Thick Dildo Sex Doll Torso for Women Masturbation, Long Bendable TPE Dildo Torso for Man, Female Masturbator Unisex Adult Toy for Solo Pleasure TPE Skin-Friendly Material (Dark)', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_9dc0b27b.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 11, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Chiseled Chad Male Love Doll', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_9d177d0b.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 12, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('1LB Realistic Torso Sex Doll,TPE Male Masturbator,Adult Sex Toy for Men | Portable Torso Sex Doll with Pocket Pussy Vaginal,Lifelike Real Solid Dolls for Sex with Breasts Boobs Butt Ass,Sex Love Doll', 4999.0, 'Realistic Torso Sex Doll Portable,TPE Male Masturbator with Pocket Pussy Vaginal,Lifelike Real Solid Dolls for Sex with Breasts Boobs Butt Ass,Adult Sex Toy for Men,Sex Love Doll', '["/products/prod_doll_5fe5f45d.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 13, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('FST Male Exterior Shape Sex Doll with 7 Inch Erection Penis and 3D Realistic Muscle Design Love Doll for Women with Insertable Anus Hole for Gay Masturbation… Black', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_085d7042.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 14, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Sex Dolls,35LB Small Realistic Full Size TPE Silicone Sex Doll Full Body Sex Dolls,Full Size Sex Doll for Men （Comes with Random Underwear）', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_843543bf.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 15, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Hott Products Fuck Friends Amber Love Doll', 4999.0, 'Fuck Friends Love Doll Amber from Hott Products. This inflatable sex doll is a life size brunette and comes to you in the sitting position ready for you to take her sitting on top of you or doggy style! Her warm tight ass and specially contoured vagina will make you explode every time! Amber will most definitely take your next sexual sensual encounter to a new level! Features: life size inflatable triple hole Amber Love Doll realistic, molded face, realistic eyes and long eyelashes. Mouth, Vagina, Anus material PVC. Sitting position. Realistic enhanced lips. Soft perky breasts and erect pink nipples. Amazingly realistic pussy lips. USB warming stick. Vibrating egg. Sensual sound effects. Waterproof vibrations. Tight pear shaped ass. Super soft realistic anus. UPC 818631031474.', '["/products/prod_doll_f7a8ab64.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 16, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('CalExotics Novelties The Blonde Starlet, Ivory (SE-1929-10-3)', 4999.0, 'CalExotics, led by its founder Susan Colvin, began in 1994 from a vision to create more inspiring intimate products that better suit the needs of people looking to enhance the pleasure in their daily lives.CalExotics produces a wide variety of products in every price range. Each product is backed by a one-year manufacturer warranty.Explore a World of Enhanced Pleasure with CalExotics.', '["/products/prod_doll_70ef645f.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 17, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('35.7 LB Full Size Sex Doll Silicone for Men Anime Pocket Life Size Sex Doll Torso Masturbation for Men Pleasure', 4999.0, '35.71 LB Sex Doll Silicone Male Masturbators Realistic Life Size Torso Male Stroker Sex Toy with Pocket Pussy Ass for Mens Masturbation, Silicone Adult Butt Toy for Men Pleasure', '["/products/prod_doll_d39dc277.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 18, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('24lb Adult Sex Doll Male Masturbator, 4 in 1 Female Torso Love Doll with Big Boobs, Big Ass, 3D Realistic Torso Sex Dolls Masturbation Penetrable Nipples Sex Doll for Men', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_27b00af0.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 19, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('CalExotics Vivid RAW Juicy Juggs LUV Doll', 4999.0, 'CalExotics, led by its founder Susan Colvin, began in 1994 from a vision to create more inspiring intimate products that better suit the needs of people looking to enhance the pleasure in their daily lives.CalExotics produces a wide variety of products in every price range. Each product is backed by a one-year limited manufacturer warranty.Explore a World of Enhanced Pleasure with CalExotics.', '["/products/prod_doll_caa183df.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 20, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('1.2LB Realistic Torso Sex Doll,TPE Male Masturbator,Adult Sex Toy for Men | Portable Torso Sex Doll with Pocket Pussy Vaginal,Lifelike Real Solid Dolls for Sex with Breasts Boobs Butt Ass,Sex Love Doll', 4999.0, 'Realistic Torso Sex Doll,Portable Sex Love Doll,Lifelike TPE Male Masturbator with Pocket Pussy Vaginal,Real Solid Dolls for Sex,Adult Sex Toy for Men', '["/products/prod_doll_56a2d870.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 21, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Accessories for Full Size Sex Doll, Care Kit Maintain Bundle for Sexdoll Torso Male Adult Toy, Heating Rod, Drying Stick, Cleaning Brush, Vagina Anal Cleaner, Essentials Set for Real Love Doll - Black', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_9b43c18a.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 22, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('D Cup BBW Torso Doll, 44.09 LB Full Size TPE Curvy Torso, Soft-Touch Realistic Body Form, Heavy Stable Adult Masturbator Toy for Men', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_fb982e87.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 23, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Shemale Sex Doll Torso Dildo - AUSLOVE Male Sex Toy with Flexible Dildo for Women, Breasts and Anal Sex, Unisex Love Doll for Men Gay Couple, Transsexual Torso Toy with Huge Dildo, Brown', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_cc634a11.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 24, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('12LB Lifelike Life Size Sex Doll Torso for Men, Realistic Full Body with Flexible Skeleton, Soft Big Breasts & Plump Butt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_e847c8e4.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 25, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Sexpower 14LB Lifelike Female Sex Dolls for Men | 3-in-1 Realistic Torso Male Sex Toys for Men, Male Masturbator Adult Toys', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_ec59b9fc.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 26, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('TANTALY 18.7LB Sex Doll with 6 Large Inner Beads Pussy Tight Ass for Intense Stimulation, Male Masturbator Ultra-Soft Stroker with 2 Closed-Ended Holes for Men Masturbation, Cecilia (Fair)', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_c3c1f9d2.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 27, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Mini Sex Doll Male Masturbator with Realistic Vagina, Small Torso Masturbator Love Doll Pocket Pussy with Boobs Vagina Sex for Men-Flesh', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_b74e58db.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 28, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Mini Sex Doll Male Masturbator with 3 Real 3D Channels, Portable Adult Sex Doll with Penetrable Big Nipples, Small Female Torso Love Doll with Realistic Pocket Pussy for Men Masturbation', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_fa5b2e0a.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 29, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Realistic Woman Torso Sex Doll TPE Silicone Love Doll with Soft Breasts Full Size Sex Doll', 4999.0, 'Production Specifications :🥰【Ht】:5.26F/T👙【Bust】: 95 cm 🤩【Waist】: 60 cm👙【Hip】: 86 cm 😘【Net weight】: 36 kg', '["/products/prod_doll_cc7d1e01.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 30, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('1.6LB Pregnant Sex Doll Mini Male Masturbator, Small Pocket Pussy with Dual 3D Realistic Pussy Ass Channels, Pregnant Sex Dolls for Men Masturbation and Orgasm, 1.6LB', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_3c9f1116.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 31, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Male Masturbator Sex Doll with 3D Textured Vagina & Anal and Boobs, 7.2LB | 3 in 1 Torso Masturbator Love Doll, Pocket Pussy Ass Male Sex Toy for Men Masturbation, Flesh', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_bbea7b6c.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 32, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Realistic Pocket Pussy for Men with Two Texture Fleshy Channels | BIG SHOCKED Male Masturbator with Extended Vagina & Anal Tunnel, TPE Soft Tight Wrap Stimulation Mens Light Sex Doll', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_21221a15.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 33, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('3D Diana Ultra Lifelike Full Size Mega Sex Doll', 4999.0, 'This super realistic, exquisitely detailed, fully life sized, 3D mega masturbator is the ultimate in sex dolls. The layered rubber features multiple densities, to perfectly mimic the feel of real flesh over muscle. Her perky breasts are full, luscious, and topped by pretty pink nipples. Her vagina features both inner and outer labia for an incredibly lifelike feel. She offers an exceptionally lifelike textured interior with a firm grip. More than just the standard ribbing, the interior of her vagina is patterned to feel exactly like the real thing. Her pink butt tunnel is also realistically textured and molded internally to simulate the feel of a real body. Nothing else comes close in terms of lifelike detailing and true-to-body craftsmanship. Soft, firm butt; petite waist and taut abs. Measurements: 26 inches in length, 13 inches in width, 9 inches in height. Material: SexFlesh (TPR). Color: Flesh.', '["/products/prod_doll_1a9ab5d2.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 10, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Male Sex Toys Built in Metal Skeleton TPE Silicone Sex Dolls Adult Toys with Big Boobs Full Size Sex Dolls Lifelike Female Torso Realistic Love Doll', 4999.0, 'Production Specifications :🥰【Ht】:5.25F/T👙【Bust】: 90 cm 🤩【Waist】: 60 cm👙【Hip】: 85 cm 😘【Net weight】: 35 kg', '["/products/prod_doll_012a002a.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 11, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Blush Sex Toy Renewal Powder 3.4 oz Bottle - Refreshes TPE/TPR Strokers, Dildos & Sex Dolls - Maintains Soft Lifelike Feel - Body Safe Cornstarch-Based Dusting Powder for Adult Sex Toys - (White)', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_c534f759.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 12, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('57LB Life Size Sex Doll for Men, Male Masturbator Realistic Female Torso Sex Toys with Lifelike Tight Vaginal Anal Big Boobs and Ass, Adult Love Doll for Mens Stroker', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_1bfb0bdb.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 13, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('5.15ft Full Size Love Doll with Soft Skin, Standing Support, Full Body TPE Sex Dolls TPE Adult Toy Poseable Skeleton Sex Doll', 4999.0, 'Immerse yourself in a luxurious experience with life-sized sex dolls meticulously crafted from premium silicone. These dolls are more than toys—they are companions designed specifically for male pleasure. Featuring soft, swaying hips and lifelike gel breasts, these male sex dolls are ingeniously crafted with an unwavering commitment to ultimate realism and comfort. 

Hight: - 5.15 FT/61.8 Inch - 

Bust: - 26.38 Inch、Waist: - 18.9 Inch、Hip: - 30.31 Inch、Weight: - 61.73 lb- 

- Skin Tone: as shown 

- Material: TPE + Silicone 

- Standing Features: YES 

- Packaging Information: - 

- Sex Dolls 

- Cozy Blanket 

- Sexy Underwear 

- Cleaning Kit 

- Styling Comb 

- Heating Rod 

- Cotton Gloves 

- Instruction Manual 

 -- You can receive your Sex doll in about 2-7 days, no long waiting time.  

- Suggestion: - 

1.Please dry with a towel after cleaning and apply talcum powder. let it dry naturally. 

2.Be careful when moving the doll, avoid dropping / knocking / breaking. Don\'t wear e', '["/products/prod_doll_42ca6445.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 14, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('4.6FT Sex Doll, 55LB Sexy Doll, Realistic Torso Love Doll, FeetStanding Life Size Sex Dolls with Jelly Breast, Flexible Skeleton Sexual Desire Toy', 4999.0, 'Immerse yourself in a luxurious experience with life-sized sex dolls meticulously crafted from premium silicone. These dolls are more than toys—they are companions designed specifically for male pleasure. Featuring soft, swaying hips and lifelike gel breasts, these male sex dolls are ingeniously crafted with an unwavering commitment to ultimate realism and comfort. 

Hight: - 4.6 FT/55.1 Inch - 

Bust: - 31.1 Inch、Waist: - 20.47 Inch、Hip: - 29.92 Inch、Weight: - 55lb- 

- Skin Tone: as shown 

- Material: TPE + Silicone 

- Standing Features: YES 

- Packaging Information: - 

- Sex Dolls 

- Cozy Blanket 

- Sexy Underwear 

- Cleaning Kit 

- Styling Comb 

- Heating Rod 

- Cotton Gloves 

- Instruction Manual 

 -- You can receive your Sex doll in about 2-7 days, no long waiting time.  

- Suggestion: - 

1.Please dry with a towel after cleaning and apply talcum powder. let it dry naturally. 

2.Be careful when moving the doll, avoid dropping / knocking / breaking. Don\'t wear easily', '["/products/prod_doll_e597782c.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 15, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('5.0ft Sex Doll Realistic Full Size Sex Dolls TPE Silicone Full Body for Sex Doll Female Torso Love Doll for Male Life Size Sex Dolls Lifelike Life Sized Sex Toys with Jelly Breast Butt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_308dbb21.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 16, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Realistic Sex Dolls,Life Size Love Doll,TPE Female Sex Torso Built-in Metal Skeleton Silicone Sex Doll', 4999.0, 'Production Specifications :🥰【Ht】:5.2FT👙【Bust】: 90 cm 🤩【Waist】: 49 cm👙【Hip】: 84 cm 😘【Net weight】: 35 kg', '["/products/prod_doll_46e1ae5d.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 17, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Recycled materials', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_ef73ed27.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 18, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Male Sex Doll Torso for Women 2.4FT with 8 inch Huge Dildo & 3D Tight Anus | Muscular Male Torso Sex Doll Fullsize Big Gay Sex Toy, Realistic Adult Intimate Sex Toy for Women Men Couples-Brown', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_47572169.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 20, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('2lb Small Big Boobs Sex Dolls for Men Male Masturbator with Torso and, Mini Female Love Doll 3D Realistic Adult Sex Dolls for Men with Pussy Ass Masturbation Pink', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_42a2e400.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 21, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('5.0ft Adult Sex Toys Sex Dolls, Life Size Sexy Doll Silicone TPE, Female Torso Love Doll with E-Cup Gel Breast, Lifelike Adjustable Joints Sexy hot Woman\'s Body', 4999.0, 'Immerse yourself in a luxurious experience with life-sized sex dolls meticulously crafted from premium silicone. These dolls are more than toys—they are companions designed specifically for male pleasure. Featuring soft, swaying hips and lifelike gel breasts, these male sex dolls are ingeniously crafted with an unwavering commitment to ultimate realism and comfort. 

Hight: - 5.0 FT/61 Inch - 

Bust: - 35.43 Inch、Waist: - 22.05 Inch、Hip: - 40.16 Inch、Weight: - 81.57 lb- 

- Skin Tone: as shown 

- Material: TPE + Silicone 

- Standing Features: YES 

- Packaging Information: - 

- Sex Dolls 

- Cozy Blanket 

- Sexy Underwear 

- Cleaning Kit 

- Styling Comb 

- Heating Rod 

- Cotton Gloves 

- Instruction Manual 

 -- You can receive your Sex doll in about 2-7 days, no long waiting time.  

- Suggestion: - 

1.Please dry with a towel after cleaning and apply talcum powder. let it dry naturally. 

2.Be careful when moving the doll, avoid dropping / knocking / breaking. Don\'t wear eas', '["/products/prod_doll_71ea3454.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 22, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Baquick 13LB Life Size Realistic Sex Doll for Men, Lifelike Female Sex Dolls Torso with 3 in 1 Pocket Pussy Ass Big Boobs Tight Vaginal & Anal', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_2cb884a2.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 23, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('38LB Life Size Sex Doll for Men, Realistic Female Sex Doll Torso Male Masturbator with Soft Big Boobs Butt Pussy Ass Built in Skeleton, Full Size Love Dolls Adult Toy for Vaginal Anal Breast Sex', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_9a7e364b.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 25, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('37.5LB Life Size Sex Doll with Flexible Torso, with Realistic Full Size Body Skin Texture, Soft Butt Big Breasts Pussy Ass Masturbation Hole & Breast Sex, Realistic Adult Male Sex Dolls for Orgasm', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_116c516b.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 26, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('73LB Life Size Realistic Sex Dolls for Men, Heavyweight Lifelike Sex Doll Torso Companion with Internal Flexible Skeleton, Dual Channel Design, Adult Toys Includes Storage Bag & Drying Stick', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_fcb9b5c0.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 27, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('7LB Sex Doll Realistic Female Buttock - TPE Male Masturbator with Dual Channels (Vagina & Anus), Lifelike Skin Texture & Open-Leg Design', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_f6b2db1c.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 28, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Silicone Sex Doll Life Size with BBW Anime Sex Doll Torso, with Realistic Full Size Body Skin Texture, Gel Boobs and Pussy Ass Masturbation Hole, Realistic Adult Male Sex Dolls for Orgasm', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_4f85cefb.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 30, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('25lb Realistic Sex Doll for Men, 3-in-1 Life Size Male Masturbator with Big Breasts & Fat Plump Butt, 3D Lifelike Skin Texture Dual-Channel, Adult Dolls Come with Storage Bag Drying Stick.', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_doll_c7b59609.jpg"]', 'Men Sex Toys', 'Sex Dolls', '[]', 1, 1, 1, 5.0, 32, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Trasparent Suction Base Silicone Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_49d8bec0.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 10, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('14 inch dual head dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_f7e04085.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 11, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('With Motion and Vibration Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_38b0ec9e.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 12, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Realistic Hollow Wearable Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_5175772c.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 13, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Young Man Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_a7c0f81f.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 14, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Crazy Lover Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_ede42973.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 15, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('9 Inch pink Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_eda3876c.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 16, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo with Harness', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_9ced3f4c.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 17, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('4 Inches Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_24c7c8a2.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 18, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Small Dildo with Suction Base', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_9506f447.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 19, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Black Silicone Dildo With Strap Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_409caa7f.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 20, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('7 Inch Black Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_99fa4918.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 21, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Strap Belt Pink Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_82811069.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 22, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Black Dildo with Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_e466ae36.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 23, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Pink Realistic Silicone Dildo With Strap Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_fd37d03c.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 24, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('6 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_6895fc5d.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 25, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Pink Dildo with Strap Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_7af3bec8.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 26, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Skin Colour 10 Inches Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_7c47a5da.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 27, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Ultra Soft Hollow-Strap on Dildo with Pussy', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_fca15b16.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 28, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('6 inch black dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_81b43482.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 29, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Penis Strength Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_564d05ce.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 30, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Pink Tip Dildo with Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_5a698f09.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 31, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Silicon Strap Dildo 8.5 Curved', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_fd767006.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 32, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Silicon Dildo With Strap-on', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_9047d677.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 33, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dual Side Dildo For LGBTQ', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_9189e022.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 34, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Big Size Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_2f9efed2.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 35, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Magic Vibrator for Women', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_d98a12c9.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 36, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Rotating and vibrating Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_e2d31c49.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 37, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Inflatable 6 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_026b2b66.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 38, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Chocolate Dildo With Strap Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_476a9254.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 39, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Pink Dildo for Girls', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_b696aeae.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 40, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Penis Like Anal Plug', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_1829db0c.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 41, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Small Short Size Realistic Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_5a5e7db8.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 42, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo For Anal Pleasure', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_989e886a.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 43, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Mars Realistic Hollow Strap Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_6e875ff9.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 44, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Lesbian Dildo with Strap Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_477abfd7.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 45, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Premium 8 inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_fa538375.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 46, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo For Gay Men', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_3ab2d861.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 47, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo For Lesbian', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_a947eb6e.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 48, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Two Side Vibration Dildo for Lesbians', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_a0b1efeb.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 49, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Silicone 10 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_0936fa8f.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 50, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Chocolate Water Based Bubricant 100ml', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_2e69bdda.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 51, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Flixible Dual Side Dildo LGBTQ', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_f5322c3b.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 52, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Premium 6 inch Skin Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_84fa6518.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 53, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('12 Inch Silicone Dildo With Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_a5184402.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 54, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Black Hollow Strap Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_28a39140.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 55, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Black Big Size Huge Silicone King Kong Dildo For Women With Suction Cup', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_e8172449.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 56, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Thrusting Dildo With Clitoral Stimulation', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_b9015ea7.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 57, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Stroking Up-Down Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_c5295e5d.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 58, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo with Suction Base', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_953dfadd.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 59, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Realistic Automatic Black Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_db55cecf.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 60, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Hollow Strap-on Dildo With Vibrator', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_fb0f6801.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 61, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Strawberry Water Based Lubricant 100ml', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_07f7a24f.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 62, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('7 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_fd098c60.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 63, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Pink Dildo With Suction Base', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_83d0070b.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 64, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dual pleasure rabbit vibrator and clitoral stimulator', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_3a7ffbe5.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 65, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('8 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_b0cd2f76.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 66, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('5 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_f0697ee9.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 67, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Pink Silicone Suction base 8 Inch Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_d2b39dc6.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 68, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('8 Inch Dildo With Belt', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_8193ec46.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 69, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo With Vibration', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_c1fe3f50.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 70, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Dildo with Vibration and Suction Base', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_5c3fb744.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 71, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Thrusting Dildo Sex Toys Dildos | Adult Sex Toy Realistic Vibrator', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_a8404c4a.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 72, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Silicon Dildo With Strong Suction Cup', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_53222052.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 73, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Black Vibrating Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_64fd854e.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 74, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Adam 7 Inch Vibrating Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_006006f9.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 75, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('10 Inch Hulk Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_12cebb7c.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 76, 'Default', 'Standard', NOW(), NOW());
INSERT INTO Product (name, price, description, images, category, subcategory, features, isNew, isBestSeller, isOnSale, rating, reviews, color, silhouetteType, createdAt, updatedAt)
VALUES ('Hollow Strap-on Dildo', 4999.0, 'Experience premium pleasure with this meticulously designed adult wellness product. Crafted from body-safe, high-quality materials for your ultimate satisfaction.', '["/products/prod_dildo_7a654e70.jpg"]', 'Women Sex Toys', 'Dildos', '[]', 1, 1, 1, 5.0, 77, 'Default', 'Standard', NOW(), NOW());